import Navbar from './Components/Navbar/Navbar';
import './globals.css';


export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='md:container md:mx-auto'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
